"""empty message

Revision ID: 29471254b39f
Revises: f4d1e2e98a9d
Create Date: 2021-08-05 12:05:06.555333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29471254b39f'
down_revision = 'f4d1e2e98a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gunpla',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('customize_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creation_time', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('gunpla')
    # ### end Alembic commands ###
